#!/usr/bin/env python3

from pathlib import Path
from snakemake.logging import logger


# tool config (different to run config)
configfile: "config/tools.yaml"


# order is important, e.g. utils has functions needed by braker3
include: "rules/utils.smk"
include: "rules/collect_rnaseq_data.smk"
include: "rules/braker3.smk"
include: "rules/tiberius.smk"
include: "rules/qc.smk"


rule collect_annotation:
    input:
        result_file=Path("results", "run", "{genome}", "{tool}", "{result_file}"),
    output:
        result_file=Path("results", "{genome}", "{tool}", "annotation", "{result_file}"),
    shell:
        "cp {input.result_file} {output.result_file}"


rule target:
    default_target: True
    input:
        expand(get_results(), genome=all_genomes),
