genomes:
  test_genome_without_rnaseq:
    augustus_dataset_name: "cacao"
    busco_lineage: "embryophyta_odb12"
    fasta_file: "test-data/genome.fa.gz"
    helixer_lineage: "land_plant"
    label: "Arabidopsis fragment"
    ncbi_family: "Brassicales"
    orthodb_division: "Viridiplantae"
    softmasked: True
    taxon_id: 3702
    tiberius_model: "Eudicotyledons"
    overrides:
      funannotate:
        busco_lineage: "embryophyta_odb10"
  test_genome_with_rnaseq:
    augustus_dataset_name: "cacao"
    busco_lineage: "embryophyta_odb10"
    fasta_file: "test-data/genome.fa.gz"
    helixer_lineage: "land_plant"
    label: "Arabidopsis fragment with RNAseq"
    ncbi_family: "Brassicales"
    orthodb_division: "Viridiplantae"
    rnaseq: "test-data/RNAseq.bam"
    softmasked: True
    taxon_id: 3702
    tiberius_model: "Eudicotyledons"
    overrides:
      funannotate:
        busco_lineage: "viridiplantae_odb10"
  test_genome_run_softmasking:
    label: "RepeatMasker test"
    augustus_dataset_name: "Ptychodera_flava"
    busco_lineage: "metazoa_odb10"
    fasta_file: "https://raw.githubusercontent.com/Dfam-consortium/RepeatMasker/refs/heads/master/t/seqs/fastaformat/simple-good-large.fa"
    helixer_lineage: "invertebrate"
    taxon_id: 51511
    tiberius_model: "Fungi"
    ncbi_order: "Phlebobranchia"
    orthodb_division: "Fungi"
    run_softmasking: True
  taxid2792576:
    label: "Rhynchosporium graminicola"
    augustus_dataset_name: "botrytis_cinerea"
    busco_lineage: "helotiales_odb10"
    fasta_file: "https://usegalaxy.org.au/api/datasets/a6e389a98c2d1678c6c46cb90b87fe92/display?to_ext=fasta"
    helixer_lineage: "fungi"
    taxon_id: 2792576
    tiberius_model: "Fungi"
    ncbi_order: "Helotiales"
    orthodb_division: "Fungi"
    run_softmasking: True
parameters:
  busco_min_training_models: 7
