

test: 
	snakemake \
		--profile profiles/local \
		--configfile config/test.yaml \
		--keep-going \
 		results/test_genome_without_rnaseq/funannotate/qc/funannotate.gff3/annooddities/AnnoOddities.tar.gz
