

test: 
	snakemake \
		--profile profiles/local \
		--configfile config/test.yaml \
		--keep-going \
		results/test_genome_with_rnaseq/funannotate/qc/funannotate.gff3/annooddities/AnnoOddities.combined_statistics.json \
		results/test_genome_with_rnaseq/funannotate/qc/funannotate.gff3/atol_qc_annotation/omark_summary.json \
		results/test_genome_without_rnaseq/funannotate/qc/funannotate.gff3/annooddities/AnnoOddities.combined_statistics.json \
		results/test_genome_without_rnaseq/funannotate/qc/funannotate.gff3/atol_qc_annotation/omark_summary.json



